version: "3.9"
services:
  backend-flask:
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
    healthcheck:
      # The --fail option in curl is used to fail silently and exit with a non-zero status code 
      # if the HTTP response status code is not successful (i.e., not in the 200-299 range). 
      # This is commonly used in scripts to determine if a resource is available or not.
      test: "curl --fail ${BACKEND_HEALTH_CHECK_URL}"
      interval: 30s
      timeout: 10s
      retries: 3
  frontend-react-js:
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
      - /frontend-react-js/node_modules
  # xray-daemon:
  #   image: "amazon/aws-xray-daemon"
  #   command:
  #     - "xray -o -b xray-daemon:2000"
  #   ports:
  #     - 2000:2000/udp

  dynamodb-local:
    # https://stackoverflow.com/questions/67533058/persist-local-dynamodb-data-in-volumes-lack-permission-unable-to-open-databa
    # We needed to add user:root to get this working.
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks: 
      - internal-network

# the name flag is a hack to change the default prepend folder
# name when outputting the image names
networks: 
  internal-network:
    driver: bridge
    name: cruddur

volumes: 
  db: 
    # this means we'll be storing the data locally on the machine 
    # where the containers will be running.
    driver: local